Projet/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Projet import settings
from Projet.views import index, create_recipe, recipe_list, register, my_recipe, about

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('home', index, name='index'),
    path('recipe/create', create_recipe, name='create_recipe'),
    path('recipe_list/<name>', recipe_list, name='recipe_list'),
    path('my_recipe', my_recipe, name='my_recipe'),
    path("register/", register, name="register"),
    path("about/", about, name="about"),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projet/models.py
from django.db import models
from django.conf import settings

User = settings.AUTH_USER_MODEL


class Recipe(models.Model):
    title = models.CharField(null=False, max_length=100)
    photo = models.ImageField(upload_to="pictures/", null=True, blank=True)
    ingredients = models.TextField(null=False)
    times = models.IntegerField(null=False, verbose_name="Temps de préparation en minutes")
    guide = models.TextField(null=False)
    category = models.ForeignKey(
        "RecipeCategory",
        related_name="structures",
        on_delete=models.PROTECT,
        verbose_name='category',
        blank=True,
        null=True
    )
    user = models.ForeignKey(
        User,
        default = 1,
        null = True,
        on_delete = models.SET_NULL
    )

    class Meta:
        verbose_name = "Recette"
        ordering = ("title",)

    def __str__(self):
        return self.title


class RecipeCategory(models.Model):
    name = models.CharField(null=False, blank=False, max_length=100)

    class Meta:
        verbose_name = "Category de recette"
        ordering = ("name",)

    def __str__(self):
        return self.name

Projet/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from Projet.models import Recipe
from django.contrib.auth import password_validation

class RecipeForm(ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'photo', 'category', 'ingredients', 'times', 'guide']


class SearchRecipeForm(forms.Form):
    name = forms.CharField(label='Rechercher une recette', max_length=100, required=False)


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

Projet/views.py
from django.http import HttpResponse
from Projet.models import Recipe
from django.shortcuts import render, redirect
from Projet.forms import RecipeForm, SearchRecipeForm, RegisterForm
from django.contrib import messages
from django.contrib.auth import login


def index(request):
    recipes = None
    if request.method == 'POST':
        form = SearchRecipeForm(request.POST)
        if form.is_valid():
            if form.cleaned_data.get('name') != '':
                recipes = Recipe.objects.filter(title__icontains=form.cleaned_data.get('name'))
    else:
        form = SearchRecipeForm()
    return render(request, "Index.html", {"recipes": recipes, 'form': form})


def recipe_list(request, name):
    recipes = Recipe.objects.filter(category__name=name)
    return render(request, "recipes.html", {"recipes": recipes})


def my_recipe(request):
    recipes = Recipe.objects.filter(user=request.user)
    return render(request, "recipes.html", {"recipes": recipes})


def about(request):
    return render(request, "about.html")


def create_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save()
            recipe.user = request.user
            recipe.save()
            return redirect('index')
    else:
        form = RecipeForm()
    return render(request, 'create_recipe.html', {'form': form})


def register(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("index")
        messages.error(request, "Unsuccessful registration. Invalid information.")

    return render(request, "registration/register.html", {"form": form})

Projet/templates/Index.html
{% extends "base.html" %}

{% block content %}

    <!-- Barre de recherche -->
        {% if form %}
            <div class="wrap">
                <form method="post" class="searchTerm">
                    {% csrf_token %}
                    <label for="id_name"></label>
                    <input type="text" class="input" name="name" maxlength="100" id="id_name" placeholder="Que recherchez-vous ?">
                    <button type="submit" class="searchButton">
                        <i class="bi bi-search"></i>
                    </button>
                </form>
            </div>
        {% endif %}
 {% if recipes.count == 0 %}
            <div class="text">Aucune recette trouvée</div>
        {% else %}
            <div class="card-group">
                {% for recipe in recipes %}
                    <div class="card" style="max-width: 400px; min-width: 300px; margin: 30px">
                        {% if recipe.photo %}
                            <img class="card-img-top" src="{{ recipe.photo.url }}" alt="Card image cap" style="max-height: 250px">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.title }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ recipe.times }} min</h6>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ recipe.ingredients }}</li>
                            <li class="list-group-item">{{ recipe.guide }}</li>
                        </ul>
                        <div class="card-footer">
                            <small class="text-muted">{{ recipe.user }}</small>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

    <!-- Le blabla pour remplir la page-->
      <div>
        <h1>Bienvenue sur Wiki'Food !</h1>
        <p>Wiki'Food est un projet collaboratif en ligne. Le but ? Créer le plus gros livre de recette au monde fait pour et par les utilisateurs !<br>
            Alors, pour réussir notre objectif, on compte sur vous ! (... Comment ça ce slogan est déjà pris ?)</p>
      </div>
    <h2 class="title-container">L'actualité</h2>

    <div class="row" style="margin-right: 0">
        <div class="col" style="text-align: center">
            <div class="board-blabla">
                <h3>Qui dit hiver dit... Raclette ! (On vous jure, ça rime)</h3>
                <p class="text">
                    Cette merveilleuse création culinaire est au centre de bien des conversations en ce moment. L'un des sujets qui revient le plus souvent est le suivant : pour ou contre la raclette toute l'année ?
                    Bien sur, Wiki'Food ne pouvait pas passer à côté d'un débat aussi clivant, et pour essayer de vous donner une idée de quelle tendance l'emporte, l'équipe a été chercher des réponses auprès de nos utilisateurs les plus réguliers !<br>
                    Et sans plus tarder, voici les résulats !
                </p>
            </div>

            <!-- Le tableau-->
            <div class="wrap-board">
                <table class="board">
                    <tr class="line">
                        <th class="cell1"></th>
                        <th class="cell2">Pour</th>
                        <th class="cell3">Contre</th>
                        <th class="cell4">Le fromage est une invention du diable</th>
                    </tr>
                    <tr class="line">
                        <td class="cell1">Jules</td>
                        <td class="cell2"></td>
                        <td class="cell3"></td>
                        <td class="cell4">X</td>
                    </tr>
                    <tr class="line">
                        <td class="cell1">Mélissa</td>
                        <td class="cell2"></td>
                        <td class="cell3"></td>
                        <td class="cell4">X</td>
                    </tr>
                    <tr class="line">
                        <td class="cell1">Édouard</td>
                        <td class="cell2">X</td>
                        <td class="cell3"></td>
                        <td class="cell4"></td>
                    </tr>
                    <tr class="line">
                        <td class="cell1">Nolwenn</td>
                        <td class="cell2"></td>
                        <td class="cell3">X</td>
                        <td class="cell4"></td>
                    </tr>
                    <tr class="line">
                        <td class="cell1">Lauren</td>
                        <td class="cell2"></td>
                        <td class="cell3">X</td>
                        <td class="cell4"></td>
                    </tr>
                    <tr class="line">
                        <td class="cell1">Maël</td>
                        <td class="cell2">X</td>
                        <td class="cell3"></td>
                        <td class="cell4"></td>
                    </tr>
                    <tr class="line">
                        <td class="cell1">Diego</td>
                        <td class="cell2"></td>
                        <td class="cell3">X</td>
                        <td class="cell4"></td>
                    </tr>
                    <tr class="line">
                        <td class="cell1">Manon</td>
                        <td class="cell2">X</td>
                        <td class="cell3"></td>
                        <td class="cell4"></td>
                    </tr>
                    <tr class="line">
                        <td class="cell1">Jérémy</td>
                        <td class="cell2"></td>
                        <td class="cell3">X</td>
                        <td class="cell4"></td>
                    </tr>
                    <tr class="line">
                        <td class="cell1">Bastien</td>
                        <td class="cell2">X</td>
                        <td class="cell3"></td>
                        <td class="cell4"></td>
                    </tr>
                    <tr class="line">
                        <td class="cell1">Simon</td>
                        <td class="cell2"></td>
                        <td class="cell3"></td>
                        <td class="cell4">X</td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col" style="text-align: center">
            <div class="video-blabla">
                <h3>Parce qu'en hiver,  il n'y a pas que la raclette !</h3>
                <p class="text">Et oui, en hiver il y a aussi Noël ! Voici donc la vidéo de bûche qui a recueilli le plus d'avis favorable de la part de nos utilisateurs !</p>
            </div>
            <div style="text-align: center">
                <iframe class="video" width="560" height="315" src="https://www.youtube.com/embed/zrlJbCma31Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
    </div>
{% endblock %}

Projet/templates/about.html
{% extends "base.html" %}

{% block content %}
<div class="about-container">
    <div class="text">
        Ce site est le fruit d'un délire avec mes amis. Je leur ai parlé de mon sujet de dossiers, puisque la plupart d'entre eux font des études dans l'informatique. <br>
        Même si tout le monde n'a pas tout compris, une chose était sûre : un site parlant de nourriture ne pouvait qu'être une bonne idée.
        Cuisiner faisant partie de mes occupations favorites, je n'ai pu qu'être d'accord avec eux.<br>
    </div>
    <div class="text">J'ai la chance d'avoir déjà des bases en code puisque j'en fais avec mes amis, mais je me concentre surtout sur le code pur.
        J'aime les design sobres et épurés, c'est pour cela que mon site garde une apparence très simple, mais je suis me suis amusée avec le code html et python.
        J'aurai pû faire des choses plus... élaborées en CSS, mais je n'arrivais pas l'intégrer dans mon site. Ou, plutôt, ce n'était pas à mon goût.<br>
        J'ai, par exemple, voulu faire une barre de recherche originale (essayez de taper quelque chose dans la barre pour voir toute l'animation)
    </div>
<form class="form-search-about">
	<label for="search">Search</label>
	<input class="input-about" type="search" pattern=".*\S.*" required>
	<span class="caret"></span>
</form>
<div class="text"> mais je trouvais que cela ne collait pas du tout avec le reste, j'ai donc opté pour quelque chose de plus simple, plus en accord avec le reste du site.
    Et puisque je n'aime pas utiliser javascript, toute l'animation est faite via CSS (une perte de temps, je sais, mais les habitudes ont la vie dure...)<br>
</div>
</div>
{% endblock %}

Projet/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Wiki'Food</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">    </head>
    <body>
    <!-- Mise en place du menu avec boucle de condition pour un affichage différent si connecté avec un compte ou non -->
        <nav class="menu">
            <ul class="ssmenu">
                <li><a href="{% url 'index' %}">Page d'accueil</a></li>
                <li><a href="{% url 'recipe_list' 'Entrées' %}">Entrées</a></li>
                <li><a href="{% url 'recipe_list' 'Plats' %}">Plats</a></li>
                <li><a href="{% url 'recipe_list' 'Desserts' %}">Desserts</a></li>
                <li><a href="{% url 'recipe_list' 'Encas' %}">Encas</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'my_recipe' %}">Mes recettes</a></li>
                    <li><a href="{% url 'create_recipe' %}">Poster une recette</a></li>
                {% endif %}
                <li><a href="{% url 'about' %}">À propos</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Se déconnecter</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Se connecter</a></li>
                    <li><a href="{% url 'register' %}">Créer un compte</a></li>
                {% endif %}
            </ul>
        </nav>
        {% block content %}
        {% endblock %}
    <div class="footer">
    <div class="team">
        <p class="text-bottom">Site créé et géré par la team MCP.<br>
        Merci de ne pas plagier le site : on est gentil tout le monde peut utiliser celui-ci.
        </p>
    </div>
    <div class="contacts">
        <p class="text-bottom"> Vous souhaitez nous contacter, vous pouvez le faire via discord auprès de Idalys#2298.<br>
            Ou vous pouvez nous retrouver sur le  <a class="link" href="https://discord.gg/MDwzvybDcN">discord communautaire</a></p>
    </div>
    <div class="thanks">
        <p class="text-bottom">L'équipe souhaite vous remerciez. Le site n'existe que parce que vous y participez.</p>
    </div>
</div>
    </body>
</html>

Projet/templates/create_recipe.html
{% extends "base.html" %}

{% block content %}

    <div class="recipe">
        <form class="form_recipe" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div style="padding-bottom: 20px">
                    <h2>{{ field.label }}</h2>
                    {{ field }}
                </div>
            {% endfor %}
            <input class="input_recipe" type="submit" value="Poster ma recette" />
        </form>
    </div>

{% endblock %}

Projet/templates/recipes.html
{% extends "base.html" %}

{% block content %}

    <!-- Barre de recherche -->
        {% if form %}
            <div class="wrap">
                <form method="post">
                    {% csrf_token %}
                    <label for="id_name"></label>
                    <input type="text" name="name" maxlength="100" id="id_name" placeholder="Que recherchez-vous ?">
                    <button type="submit" class="searchButton">
                        <i class="bi bi-search"></i>
                    </button>
                </form>

            </div>
        {% endif %}

        {% if recipes.count == 0 %}
            <div class="text">Aucune recette trouvée</div>
        {% else %}
            <div class="text">Il y a {{ recipes.count }} recette(s)</div>
            <div class="card-group">
                {% for recipe in recipes %}
                    <div class="card" style="max-width: 400px; min-width: 300px; margin: 30px">
                        {% if recipe.photo %}
                            <img class="card-img-top" src="{{ recipe.photo.url }}" alt="Card image cap" style="max-height: 250px">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.title }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ recipe.times }} min</h6>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ recipe.ingredients }}</li>
                            <li class="list-group-item">{{ recipe.guide }}</li>
                        </ul>
                        <div class="card-footer">
                            <small class="text-muted">{{ recipe.user }}</small>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
{% endblock %}